title: Q-Data
description: Workshop on Quantum Computing and Quantum-Inspired Technology for Data-Intensive Systems and Applications
show_downloads: false
github.is_project_page: false
theme: jekyll-theme-cayman
